development:
  adapter: postgresql
  database: compass_dev
  pool: 5
  timeout: 5000
  user: bj
  password:

test:
  adapter: postgresql
  database: compass_dev
  pool: 5
  timeout: 5000
  user: bj
  password:
